# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

    steps:
    - name: Check Xcode version
        run: xcodebuild -version
      - name: runnerImage
        value: 'macOS-14'
    - name: XcodeVersion
        value: 'Xcode_15.4.app'
        - uses: actions/checkout@v4
        - run: fastlane mac run_CI_tests
