# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

    steps:
        - uses: actions/checkout@v4
         with:
            xcode-version: 16.0
        - run: fastlane mac run_CI_tests
